package com.automation.screen.uipages.interfaces.home;

public interface HomePage {
    void clickBtnMasukForLogin();
    void clickBtnDaftar();
    void clickBtnBeranda();
    void clickBtnTracking();
    void clickBtnCekTarif();
    void clickBtnkirimPaket();
    void clickBtnCariToko();
    void clickBtnTentangKamiBeforeLogin();
    void clickBtnLayananDanProgram();
    void clickBtnTutorial();
    void clickBtnMembership();
    void clickBtnLupaPassword();
    void inputResi(String noResi);
    void clickButtonMultiResi();
    void inputMultiResi(String noMultiResi);
    void clickBtnSearchResi();
    void clickButtonTentangKami();
    void insertCapcha();
    void inputAsalKota(String kotaAsal);
    void inputTujuanKota(String kotaTujuan);
    void inputBerat();
    void inputDimensiPanjang();
    void inputDimensiLebar();
    void inputDimensiTinggi();
    void clickButtonCekTarif();
    void clickButtonProfile();
    void clickDropdownMenuEditProfile();
    void clickDropdownMenuEditPassword();
    void clickButtonRiwayat();
    void clickButtonSurveyPengiriman();
    void clickButtonNotification();
    void clickButtonInfoPromo();
    void clickButtonDetilNotification();
    void clickButtonSTatusPaket();
    void clickCheckboxNotification();
    void clickButtonDeleteNotification();
    void clickButtonConfirmDeleteNotification();
    void clickButtonSuccessDeleteNotification();
    void clickButtonLihatSemuaNotifikasi();
    void clickButtonOTP();
    void clickBtnTentangKamiAfterLogin();
    void clickBtnLayananProgram();
    void clickBtnFAQ();
    void clickBtnSyaratKetentuan();
    void clickBtnKebijakan();
    void getURLInstagram();
    void getURLFacebook();
    void getURLTiktok();
    void getURLYoutube();
    String getTextOfficeAddress();
}
